### ISSUE TITLE
Support Canceling of Jobs

### ISSUE THREAD

**Issue by KuhnMn** [SeQuenC-Consortium/qunicorn-core#104]
## Problem Statement

Jobs which have been started, but are not yet finished should be cancelable.

## Expected Behaviour

If a job has not been executed yet, take it out of the celery queue.
Otherwise, try to cancel it at the provider (Probably needs to be implemented specifically for each one).
Add a method to the base_pilot.

## Tasks

- [x] Save provider specific data in the database
- [x] Add a cancel method to the base_pilot
- [x] Cancel not yet executed job by taking it out of the celery queue
- [x] Cancel job already in execution using provider-specific implementations

## Notes

Split from Issue #77 .
Subtask of #115.

**Comment by PatrickEbner** [comment]
Old estimate: 8
