### ISSUE TITLE
Update and clean-up read the docs for prototype

### ISSUE THREAD

**Issue by st161630** [SeQuenC-Consortium/qunicorn-core#111]
## Problem Statement

Frozen Prototype gives us the Chance to bring the RTD Documentation up to our current level.

## Expected Behaviour

Correct and complete Documentation

## Tasks

- [ ] Tutorial Section
  - [ ] How to run the project (Local, Docker (Compose), Kubernetes)
  - [ ] How to create a pilot (probably blank site for now)
- [ ] Current Features
- [ ] Supported Languages
- [ ] Further Description of API / Some common workflows
