### ISSUE TITLE
Create a demo use-case using the workflow modeler and camunda engine

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#112]
## Problem Statement

As a user, I want to execute a workflow, using qunicorn as a middleware for quantum circuit executions.

## Sketch

![image](https://github.com/SeQuenC-Consortium/qunicorn-core/assets/56876774/8c6c95f5-b5d8-4358-b06b-b8e9545271ad)

## References

Here is a guided tutorial as a reference:
https://ust-quantil.github.io/icwe-tutorial/handson.html

## Expected Behavior

A guided tutorial which uses all necessary tools to build a workflow with a simple quantum circuit. The Tutorial should be comprehensive similar to the reference.

More specifically, create use-cases with different possible methods. One should use a script-task for generating quantum circuits. One should use user-inputs and the user should decide on the respective pilot for execution.

## Tasks

- [x] Structure the repository https://github.com/SeQuenC-Consortium/SeQuenC-UseCases, such that more use-cases can be added
- [ ] Create a docker-compose for the demo containing all the necessary tools
    - [ ] https://github.com/UST-QuAntiL/quantil-docker Add Profiles to allow different Configurations for execution (e.g. with or without wfm tools)
- [x] Add a short description of the use-case to the README.md
- [x] Add a README.md for the use-case
- [x] Add all necessary files and information in the respective use-case folder
- [x] Add the resulting bpmn file to the repository
- [x] Establish a naming scheme for use-cases

## Notes

The reference tutorial leads to a repository which contains multiple use-cases für QuantME.
The style/structure of this repo can be used with slight modifications which serves our purpose.
Please store the groovy scripts also externally and not only inline as it is not handy to look in the inline editor.

**Comment by st161630** [comment]
Requires Merging of upstream qunicorn pull request for completion.
