### ISSUE TITLE
Execution Environments for QRISP and extendable for Rigetti

### ISSUE THREAD

**Issue by BonnetGa** [SeQuenC-Consortium/qunicorn-core#116]
## Problem Statement

We need an execution environment to execute QRISP.
An unfinished implementation of this already exists on "experimental/generic-transpile-and-exec-env".
This should be used for Rigetti aswell at a later stage, so it should be implemented with extendability in mind.

## Expected Behaviour

QRISP can be run within environments.

## Tasks

- [x] Check existing implementation
- [x] Implement execution environments
- [x] Check functionality
- [x] Add necessary Transpile methods to Transpile manager
- [x] Add a Test for QRISP
- [x] Add new requirements to requirements in docs
