### ISSUE TITLE
Add get_standard_devices method to base pilot and refactor code according to that

### ISSUE THREAD

**Issue by BonnetGa** [SeQuenC-Consortium/qunicorn-core#117]
## Problem Statement

We need to refactor the pilots to make it easy to add pilots for new provider.

## Expected Behaviour

There is no provider specific code for ibm or aws for the device manager other then the pilots.
We need a json for ibm and for aws to add there all devices that should be added to the database.
Also the regarding provider should be created in the pilot method. 
Get-Devices-From-Provider should be also moved inside the corresponding pilots.

## Tasks

- [ ] Add method to base pilot
- [ ] Implement methods for the aws pilot and use the code from cli.py
- [ ] Implement methods for the ibm pilot and use the code from cli.py
- [ ] Use the new pilot methods in cli.db

## Notes

Subtask of #115
