### ISSUE TITLE
Refactor run-method of the pilots and use the base pilot method for general code

### ISSUE THREAD

**Issue by BonnetGa** [SeQuenC-Consortium/qunicorn-core#118]
## Problem Statement

We need to refactor the pilots to make it easy to add pilots for new provider.

## Expected Behaviour

Add general code like "update status to Ready" and "update status to finished" to method in the base_pilot and use it in the aws and ibm pilot. 
Don't forget the aer_simulator for possible refactorings.
Add a IBM_utils and AWS_utils file to put there the aws and ibm specific result_mapper.

## Tasks

- [x] Add general code to method in the base pilot
- [x] Refactor IBM-Run method 
- [x] Extract the result mapper in the new utils files

## Notes

Subtask of #115
