### ISSUE TITLE
Add the execute method to the base pilot and move all sampler/upload_program... in this

### ISSUE THREAD

**Issue by BonnetGa** [SeQuenC-Consortium/qunicorn-core#119]
## Problem Statement

We need to refactor the pilots to make it easy to add pilots for new provider.

## Expected Behaviour

The base_pilot should have an  _execute-method_ that will be used for all provider-specific extra runners.
Like Sampler, Estimator, Upload-Program, Run-Program.
They need to be executed from the _execute-method._
Raise an NotImplementedError if they are tried to be executed on the AWS-Pilot.

## Tasks

- [x] Add execute to base_pilot
- [ ] Call the methods in the execute method for IBM
- [x] Raise Error for AWS

## Notes

Subtask of #115
