### ISSUE TITLE
In-Request Execution for AWS

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#13]
## Problem Statement

Qunicorn should provide different ways of how a circuit is provided for execution.
As a user i want to execute a quantum circuit on a target device where the quantum circuit code lies in the request.

## Sketch

![image](https://user-images.githubusercontent.com/56876774/233932159-5bc012f4-108d-4447-90d8-23fb71d7349d.png)

## References

<details><summary>Documentation Links (click to expand)</summary>
<p>

[https://docs.aws.amazon.com/braket/index.html](https://docs.aws.amazon.com/braket/index.html)

</p>
</details> 

<details><summary>Execution Service (click to expand)</summary>
<p>

[https://github.com/UST-QuAntiL/braket-service](https://github.com/UST-QuAntiL/braket-service)

</p>
</details> 

## Goal

A job can be executed via API call. The POST Request is processed by QUNICORN and sent to the respective quantum service provider.
The Flask Skeleton qunicorn-core contains a structure of the API Resources, where the jobmanager should handle the request.

## Tasks

---

- [x] In-Request Quantum Circuit should be executed
- [x] Results should be saved in the database
- [x] Tests for the in-request execution

## Notes

**AWS does not provide free/simple access, therefore only local simulation should be supported**

Amazon does not support an in-request with direct response, the results are saved in a S3 bucket. 

Check the documentation for API reference.

**Comment by ArneBartenbach** [comment]
Old estimate 9
