### ISSUE TITLE
Simple User Management

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#134]
Related to: #5 

## Problem Statement

A simple user management is necessary when using a hosted version of qunicorn.

## References

Here is a tool for authentication, especially useful for the docker compose/kubernetes
(https://www.keycloak.org)

## Expected Behavior

New users can be added or existing users deleted. Jobs should be associated with a user.
The GET `/jobs` should return the jobs started by the user plus the public jobs.
The GET `/deployments` should return the deployments by the user plus the public deployments.
The user management should be available via keycloak in the docker compose

## Tasks

- [ ] Implement the User-API with the simple functions
- [ ] Add keycloak to the docker compose
- [ ] Use keycloak to manage users
- [ ] (If possible with keycloak) Implement (local qunicorn) user-tokens for registered users for the usage with qunicorn
- [ ] Documentation should include an explanation of how to use keycloak with qunicorn
- [ ] Add a use-case to the `SeQuenC-UseCases` repository showing the authentication and the deployment/execution
- [ ] Update the docker-compose overview sketch

## Notes

The keycloak is only important for the docker-compose setup for the hostet version.
For simple and fast testing of other features, the local version could/should be usable without keycloak.

Subtickets: #136 and #137
