### ISSUE TITLE
Init a Keycloak container

### ISSUE THREAD

**Issue by BonnetGa** [SeQuenC-Consortium/qunicorn-core#136]
## Expected Behaviour
Runnable Keycloak container, with following configuration:
* Application for Qunicorn
* OAuth 2.0 Code flow activated
* 2 - 3 example users

## Tasks

Subtask of #134

- [x] Add keycloak to the docker compose -> Link with existing Postgres and have committable initial configuration
- [x] Use keycloak to manage users
- [x] Update the docker-compose overview sketch

Subtask of #134
