### ISSUE TITLE
Mark unused Code as WIP/Experimental

### ISSUE THREAD

**Issue by st161630** [SeQuenC-Consortium/qunicorn-core#140]
## Problem Statement

Certain Features could not be tested / properly implemented due to missing Access to Cloud.
Those should be marked in a way.

## Expected Behavior

Features are marked.

## Tasks

- [x] Decide how to mark the Features
- [x] Mark the Features
- [x] Test how it appears for the User
- [x] Document the Decisions in RTD
