### ISSUE TITLE
transpile manager and pilot documentation

### ISSUE THREAD

**Issue by st161630** [SeQuenC-Consortium/qunicorn-core#155]
## Problem Statement

The transpile manager should be documented.

The implemented Pilots should have rtd documentation

## Expected Behavior

Documentation is written.

## Tasks

- [x] Create rtd documentation for transpile manager. 
- [x] Add architectural decision record for transpile manager introduction. 
- [x] Fill rtd documentation for pilots. 
- [x] Fill architectural decision records for pilots refactoring.
