### ISSUE TITLE
Documentation planning

### ISSUE THREAD

**Issue by st161630** [SeQuenC-Consortium/qunicorn-core#158]
## Problem Statement

Creating sub-issues for the #129 

Create new issues for all documentation parts that need to be edited. 
Should be completed by end of current sprint

## Expected Behaviour

Issues have been created. 

## Tasks

- [x] Check current documentation for errors
- [x] Check for missing parts of documentation
- [x] Create list for missing parts / errors
- [x] Create Stories for the topics that have to be reworked

When we have the list of the things that need to be done, we can create the tickets and add them to the next sprint.

**Comment by st162107** [comment]
List of topics that have to be reworked in the rtd:

- Architecture Overview
- Project Structure
- Pilot and Transpilemanager Documentation
- Glossar
