### ISSUE TITLE
Documentation: Architecture Overview

### ISSUE THREAD

**Issue by st162107** [SeQuenC-Consortium/qunicorn-core#163]
## Problem Statement

Sub-issue for the https://github.com/SeQuenC-Consortium/qunicorn-core/issues/129

We need to update our rtd for our final submission and presentation.

**Location**: _Read the docs -> Architecture Documentation -> Architecture Overview_

## Expected Behaviour

In this specific issue, the Architecture Overview should be updated and reworked since it is currently outdated due to some changes. 
Especially the sections:
- Component Interactions
- Domain Model
- Sequence Diagram for in-Request execution

## Tasks

- [x] Update Component Interactions Diagram
- [x] Update Domain Model
- [x] Update Sequence Diagram
- [ ] Add/update changed/new terms of the section "Architecture Overview" to the glossary
