### ISSUE TITLE
Documentation: Project Structure

### ISSUE THREAD

**Issue by st162107** [SeQuenC-Consortium/qunicorn-core#164]
## Problem Statement

Sub-issue for the https://github.com/SeQuenC-Consortium/qunicorn-core/issues/129

We need to update our rtd for our final submission and presentation.

**Location**: _Read the docs -> Architecture Documentation -> Project Structure_

## Expected Behaviour

In this specific issue, the Project Structure should be updated and reworked since it is currently outdated due to some refactorings. 
The Project structure does currently contain:
- API
- Core
- Db
- (Static (enums))

## Tasks

- [x] Update API Structure
- [x] Update Core Structure
- [x] Update Db Structure
- [x] Add Static Structure (if necessary)
- [x] Don't forget to also check the naming of the packages
- [x] Create a less confusing page layout (e.g. add headlines and highlights)
- [x] Add/update changed/new terms of the section "Project Structure" to the glossary
