### ISSUE TITLE
Documentation: Pilot and Transpilemanager Documentation

### ISSUE THREAD

**Issue by st162107** [SeQuenC-Consortium/qunicorn-core#165]
## Problem Statement

Sub-issue for the https://github.com/SeQuenC-Consortium/qunicorn-core/issues/129

We need to update our rtd for our final submission and presentation.

**Location**: _Read the docs -> Pilot and Transpilemanager Documentation -> AWS Pilot/IBM Pilot/Transpile manager_

## Expected Behaviour

In this specific issue, the Pilot and Transpilemanager Documentation should be extended so that others working on it in the future can understand how the pilot and transpile manager concept works. 

## Tasks

- [ ] Extend AWS Pilot Documentation
- [ ] Extend IBM Pilot Documentation
- [ ] Update Transpile Manager
- [ ] Add/update changed/new terms of the section "Pilot and Transpilemanager Documentation" to the glossary
