### ISSUE TITLE
Basic Presentation Slides

### ISSUE THREAD

**Issue by st162107** [SeQuenC-Consortium/qunicorn-core#169]
## Problem Statement

We need slides for our final presentation.

## Expected Behaviour

A first design of the presentation slides.

## Tasks

- [x] get and use template from IAAS
- [x] add welcome slide (IAAS logo, title, participants, supervisors)
- [x] create master slide with date, university, institute, slide number
- [x] add introduction slides with developers (us)
- [x] add agenda for the presentation
- [x] create slides for WFM and qunicorn presentation (architecture, functionality, general overview etc.)

**Comment by st162107** [comment]
Der Dienstag 14. November 2023 um 14:30 Uhr im TPL an der Universität. 

**Grober Rahmen**: 

- 20 Minuten für Folien/Präsentation 
- 10 minuten Diskussion
- Demonstrationen 20 Minuten 
- 10 Minuten Diskussion.
