### ISSUE TITLE
Make DB models consistent

### ISSUE THREAD

**Issue by st162107** [SeQuenC-Consortium/qunicorn-core#173]
## Problem Statement

Currently the db models and their comments are not in a sorted order and should also be refactored.

## Expected Behaviour

Db models should have a consistent order of their parameters and a clean documentation (comments).

## Tasks

- [x] Refactor and clean up the db models
- [x] Remove default values in db models
- [x] Rename qiskit_circuit to circuit and add a description to the deployment api
