### ISSUE TITLE
Create Poster

### ISSUE THREAD

**Issue by BonnetGa** [SeQuenC-Consortium/qunicorn-core#180]
## Problem Statement

We need a poster for our final presentation and for the institute which gives a broad overview over qunicorn and its functionality.

## Tasks

- [ ] Link to WIP file of poster is in dev channel (pinned messages)
- [ ] Example posters are in orga channel (pinned messages)
- [ ] Brainstorm what should be on the poster (which visualizations?)
- [ ] Decide how the poster should be structured (which things should be dominant?)

## Notes

No Deadline
