### ISSUE TITLE
Check keycloak functionality and enhance docu

### ISSUE THREAD

**Issue by BonnetGa** [SeQuenC-Consortium/qunicorn-core#181]
## Problem Statement

Keycloak user identification is implemented but does not work fully.

## Expected Behaviour

Keycloak is implemented but the guide to set it up is missing.

## Tasks

- [x] Find out how to set up keycloak
- [x] Update the read the docs 
- [x] Update the readme
