### ISSUE TITLE
Finalize the presentation for review

### ISSUE THREAD

**Issue by lokmanfl** [SeQuenC-Consortium/qunicorn-core#227]
## Problem Statement

The PowerPoint slides are still in their basic state so we have to create a first version that we can send to our supervisors for review

## Tasks

- [x] Brainstorm what should be on the presentation
- [x] Fill all the slides with the brainstormed content
- [x] Create a section for image sources
