### ISSUE TITLE
Rework the Qunicorn API accoridng to REST best practises

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#233]
## Problem Statement

The Qunicorn APi should be updated to follow best practises of REST-api design.

## Expected Behavior

The functionality SHOULD not change.

## Tasks

- [ ] Change the root, such that the v1 contains a self link
- [ ] Remove the deploymentID from the body in /Jobs -> query
- [ ] Delete should just return ok or an specific error, not the whole deleted information
- [ ] run, rerun, cancel as action in the request body in /Jobs
- [x] jobs/queue as query parameter
- [x] Change the PUT -> POST in devices
- [ ] devices status -> delete provider in the request
- [ ] Implement Vendor specific token in the header, such that it can be set in an env variable
  - [ ] POST -> GET in devices
  - [ ] POST -> GET calibration
- [x] In /deployments, programs are currently a list in a string -> remove the string nesting
- [x] Implement deployment/deploymentid/programs for content
  - [x] Remove the whole circuit from other requests
- [ ] Remove the detailed output in DELETE /deployments 
- [x] Refactor in GET /provider to only return the language

## Notes

First step can be a modified version of the swagger
