### ISSUE TITLE
Move the Upstream Qunicorn Repo to the Organisation

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#234]
## Tasks

- [ ] Merge relevant issues/PRs
- [ ] Move the Upstream Repository to the SeQuenc Organisation
- [ ] Delete the forked repository

---

Note: Before deleting the fork, one meeting is necessary
