### ISSUE TITLE
Development QMWare Pilot

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#236]
## Context

Development of the QMWare Pilot

1.  POST /requests

## Tasks

- [ ] Create a QMWare Pilot
- [ ] Add QASM2 as supported language
- [ ] Implement the run-method for the QMWare pilot
- [ ] Test the Implementation with a simple QASM2 circuit against the TEST-Environment
- [ ] Create an manual Test-case which requires the API Key

## Notes

Post /requests
timetolive -> Wie lange sind daten gespeichert

Get /jobs
Page size aktuell noch nicht wichtig, im adapter 
In qunicorn page sizes hinzufügen

Get /jobs/id
Ergebnis als JSON -> Counts

GET /jobs/id/output
Log vom worker ausgeben

GET /workers/id

GET /workers

API KEY für uns, vielleicht für Abrechnung später

JWT - kann mitgesendet werden, braucht aber publicKey
Keycloak von IONOS -> als Token Provider und Management
