### ISSUE TITLE
Create Response/Result draft for discussion

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#239]
## Problem Statement

Responses in /jobs are unstructructered/dont follow best practises.

## Expected Behavior

The new response format should unify the responses of different vendors and should be easy to read and provide "expected" results.

## Tasks

- [ ] Create a draft how the response could look
- [ ] Research the common denominator of all supported frameworks
- [ ] Research vendor specific information
- [ ] Refactor Nesting with metadata, circuits, etc

## Notes

Also refactor other endpoints, where too much information is given or the information is unstructered
