### ISSUE TITLE
Circuit Cutting - Feature

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#243]
## Problem Statement

Circuit cutting is a way to reduce the circuit width and should be accessible.

## References

ref: https://github.com/UST-QuAntiL/circuit-cutting-service

## Expected Behavior

The circuit cut should be possible. 
If service not configured -> Error

## Tasks

- [ ] Implement the cutCircuit service call
- [ ] Implement the combineCircuit call
- [ ] Test with circuit-cutting workflow
- [ ] Make it part of the job-request

## Notes

Should be able to execute a use-case with it, which serves as validation
Use the PR-version of the Cutting service
