### ISSUE TITLE
Naming Conventions

### ISSUE THREAD

**Issue by st161630** [SeQuenC-Consortium/qunicorn-core#25]
## Problem Statement
Naming conventions for branch-names and commit-names / messages

## Expected Behavior
Add documentation to confluence

## Tasks
- [x] branch-name conventions
- [x] commit-names conventions
- [x] commit-message conventions

## Notes
---

**Comment by BonnetGa** [comment]
Conventions müssen noch eine [Contributions.md](http://contributions.md/) übernommen werden

**Comment by st162107** [comment]
Naming Conventions nochmal im Team ausdiskutieren

**Comment by st161630** [comment]
Naming convention mentioned in daily - decision for "/" instead of "-" made.
Changes committed and added to Contributions.md
