### ISSUE TITLE
Domain Model for In-Request Execution

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#27]
---
## Problem Statement

The domain model for this type of execution specificies what the middleware expects as input and how to proceed with it.
Driving questions are: 
 - What is a job? 
 - How does the `jobmanager` deals with `jobs`

The marshmallow model are located in `qunicorn_core/api/models`.
Routes and behaviour should be placed in `qunicorn_core/api/[]` where the `root` should always be the root path with prefix, e.g., `/jobs/` as endpoint for the `jobmanager`.

## Sketch

<details><summary>UML Example (click to expand)</summary>
<p>

![JobPilot](https://github.com/SeQuenC-Consortium/qunicorn-core/assets/56876774/45246b4a-8d11-4853-9b5a-da2859e0f890)

More Entities need to be added.

</p>

<p>

A sample interaction between different components. Note that this is a sketch and needs refinement/rework depending on how the Pilotmanager and JobPilots are implemented.

 
![InRequestExecution](https://github.com/SeQuenC-Consortium/qunicorn-core/assets/56876774/0389a3c1-bc63-45c3-8dcc-7408ef76126b)

</p>

</details>

## Expected Behavior

The result should be an initial, well documented model of the components for an In-Request solution.

## Tasks

- [x] Design a UML class diagram for Jobs and the Jobmanager
- [x] Implement the classes as stubs in the qunicorn_core with docstrings
- [x] Assign API endpoints and document such that it is visible and explanatory in the swagger-ui
- [x] Test the endpoints by providing example values
- [x] Create a sequenc diagram with a user which wants to execute a quantum circuit with all the modeled entities

## Notes

The Jobmanager should be able to schedule tasks in different ways, not just a FIFO Queue but e.g. via Round Robin.
 
[https://sequencediagram.org](https://sequencediagram.org) can be used to create sequenc diagrams.

---

**Comment by ArneBartenbach** [comment]
HTTP Verben put und patch zu dem post hinzufügen, da post alle Funktionen übernehmen kann und die anderen beinhalten sollte in Form von Parameterns

**Comment by PatrickEbner** [comment]
Erste Schätzung: 4

**Comment by ArneBartenbach** [comment]
Funktionen für In-Request Execution aus der API aufrufen
