### ISSUE TITLE
Discuss and coordinate Git workflow

### ISSUE THREAD

**Issue by st162107** [SeQuenC-Consortium/qunicorn-core#31]
## Problem Statement
We have to decide how we want to work with branches in our environment

## Tasks
- [ ] decide whether we need a 'master-dev' branch
- [ ] document and discuss workflow for issues (assign/unassign, move tickets, create pull request)
- [ ] reevaluate the current columns in the sprint overview
- [ ] reference to naming conventions (branch naming) #25 
## Notes

Just a simple meeting with everyone who is interested and wants to contribute in this issue

**Comment by ArneBartenbach** [comment]
Pull Request in Tickets verlinken, sobald der erstellt wurde.
