### ISSUE TITLE
Familiarization with IBM

### ISSUE THREAD

**Issue by BonnetGa** [SeQuenC-Consortium/qunicorn-core#34]
## Problem Statement

To find out which request-structure is used to communicate with the IBM quantum computer.

## Expected Behavior

Document all results of the tasks in RTD.

## Tasks

- [ ] Document the request-structure/JSON
- [ ] Document the results-structure/JSON
- [ ] Document the IBM Endpoints
- [ ] Check out the authentification (token format and how its added to the request)

## Notes

Substory of #8
