### ISSUE TITLE
Restructuring of qunicorn_core (add core package)

### ISSUE THREAD

**Issue by st161630** [SeQuenC-Consortium/qunicorn-core#46]
---
## Problem Statement
Adding core package with logic to qunicorn_core
## Expected Behavior
No more logic in the API packages
## Tasks
- [x] Add package
- [x] Move logic into package/directory
- [x] Remove Linting Errors
- [x] Rename necessary Enums and Classes
## Notes
[Any additional notes or context that may be helpful in understanding the issue]
---

**Comment by st161630** [comment]
Documentation for Changes: https://github.com/SeQuenC-Consortium/qunicorn-core/blob/feature/46-qunicorn-restructuring/docs/adr/0001-restructuring-of-project.md
