### ISSUE TITLE
Testing Framework (Mock usw.)

### ISSUE THREAD

**Issue by st161630** [SeQuenC-Consortium/qunicorn-core#47]
---
## Problem Statement
In qunicorn we have different calls to outside APIs, Database and also the Celery Worker.
How do we Test Methods within these restraints. Probably Using Mocks etc.

## Expected Behavior
Documentation and functional Tests for the Methods implemented so far
## Tasks
- [x] Add Tests for jobmanager
- [x] Add Documentation on how to create tests with Mocks, other tools
- [x] Possibly guide on how to structure (do we test individual methods, or end-to-end)
## Notes

**Comment by st161630** [comment]
Documented in Readme, created synchronous tests for #8, testing the celery task
