### ISSUE TITLE
Support Sampler and Estimator for IBMQ Qiskit Runtime

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#51]
## Problem Statement

Relates to #17 

Support the Qiskit Runtime Primitives namely the sampler and estimator.
They provide aditional functionality for the user to test quantum circuits.

## References

<details><summary>Primitives (click to expand)</summary>
<p>

Simple circuit examples can be found here:
[https://quantum-computing.ibm.com/services/programs/primitives](https://quantum-computing.ibm.com/services/programs/primitives)

Note that you need to authorize:

```
import numpy as np
import json

# Importing standard Qiskit libraries
from qiskit import QuantumCircuit, transpile, Aer, IBMQ
from qiskit_ibm_provider import IBMProvider
#from qiskit.tools.jupyter import *
from qiskit.visualization import *
#from ibm_quantum_widgets import *
from qiskit.providers.aer import QasmSimulator

# Loading your IBM Quantum account(s)
IBMProvider.save_account(token='APITOKEN', overwrite=True)
provider = IBMProvider()
```

It is maybe needed to `pip install qiskit_ibm_provider qiskit_ibm_runtime ipywidgets`

A tutorial can be found here: [https://qiskit.org/ecosystem/ibm-runtime/tutorials/qpe_with_sampler.html](https://qiskit.org/ecosystem/ibm-runtime/tutorials/qpe_with_sampler.html)

A more concise test setting is here:

```
from qiskit import *
from qiskit_ibm_runtime import QiskitRuntimeService
from qiskit_ibm_runtime import Sampler

service = QiskitRuntimeService()
backend = service.get_backend("ibmq_qasm_simulator")

qc = QuantumCircuit(2)
qc.h(0)
qc.cx(0,1)
qc2 = qc
qc2.h(0)
qc.measure_all()
qc2.measure_all()

qc_qasm = qc.qasm(True)


# Sampler needs a sequence of quantum circuits
# User should be 
print(qc_qasm)

sampler = Sampler(session=backend)

# In this case with 2 quantum circuits
# job = sampler.run([qc,qc2])

# Here with just one circuit
job = sampler.run([qc])
print(f"job id: {job.job_id()}")
result = job.result()
print(f" > Quasi probability distribution: {result.quasi_dists[0]}")
```

which is directly copied out of a ipynb and useable when set up the account.

</p>
</details> 

## Expected Behavior

The User should have the ability to use the sampler and estimator primitives.
It should be an option to register a job as a sampler or estimator job with multiple quantum circuits and possibly additional properties.
The exmaples are sampler but also apply on the estimator, which is similar to implement.

## Tasks

- [x] The user can register a job with multiple quantum circuits in the qunicorn backend
- [x] The results should also be saved and accessible via GET request with the respective id
- [x] Document the simple test cases, no CI/CD but manual test should be available

## Notes

To ensure, the results are as expected compare the results in the database with the data in the IBMQ Quantum lab. In the Web UI, there is an entry with Jobs, where all the data can be observed including graphical representations.
