### ISSUE TITLE
Add IBM Backends to the Database

### ISSUE THREAD

**Issue by BonnetGa** [SeQuenC-Consortium/qunicorn-core#53]
## General
Add all important simulators and quantum computers from IBM to our database.
Something like IBMProvider.getBackends() gives us a list of backends. They are also visible [here](https://quantum-computing.ibm.com/services/resources?tab=simulators).
Therefore, the devices should be saved in connection with the IBM-Provider.
This should happen, when the database is initialized.

To make automated tests, we need to simulate on our local machine. 
Therefor we need the [aer_simulator ](https://qiskit.org/documentation/tutorials/simulators/1_aer_provider.html).
And Noise Model ?

Standard should be the airsimulator, so we do not always send requests to IBM 

## Tasks

- [x] Find out which backends/simulators/quantum-computer IBM has and select the important ones
- [x] Update devices when user sends request
- [x] Provide all devices and information in response of request
- [x] Create a method to save all devices in the database (Therefor the database need to be extended)
- [x] Implement get-all-device request (to update devices for this specific user)
- [x] Extend the Job-Request-Dto with the device_name/id and use this in the code.
- [x] Add aer_simulator to simulate on local machine (for local tests)

**Comment by st162107** [comment]
There are different backends for the aer_simulator, we currently use qasm_simulator. Is it necessary to choose between different backends or is it just fine for tests and local testing to only have one backend?
