### ISSUE TITLE
Async tests for in-request execution

### ISSUE THREAD

**Issue by st161630** [SeQuenC-Consortium/qunicorn-core#68]
Dependent on: #69 

## Problem Statement
Currently the tests in qunicorn only use synchronous execution, because mocks do not work when using the celery worker. This can be fixed by using the Aer Simulator for test exeuction.  

Those new tests could be used in parallel to the current synchronous tests. 

## Tasks
- [ ] Add Async Testing to automated testing
- [ ] Add Async Testing to manual testing
- [ ] Check for further tests

## Notes
[Any additional notes or context that may be helpful in understanding the issue]
