### ISSUE TITLE
Rework IBM Backends and corresponding requests

### ISSUE THREAD

**Issue by st162107** [SeQuenC-Consortium/qunicorn-core#69]
## General
Follow-up issue to #53 

While working on #53 multiple small things came up that should be fixed.

## Tasks

- [x] Make token not necessary when aer_simulator is used
- [x] Write tests for device request and update in database
- [x] Write tests for aer_simulator
- [x] There are different (12) aer_simulator backends, should we also be able to use them? (currently only one used)
- [x] Database instantiation without the first device which is basically empty
- [x] PUT request for devices with provider as parameter to also make AWS backends possible
- [x] Fix the entry for the job executed_on_id
- [x] Send error message when invalid token passed with put request for devices
- [x] Add logging for new functions
- [x] Remove Url from DeviceDto and DeviceDataclass

**Comment by st162107** [comment]
-> Sollen bei get-devices alle devices zurückgegeben werden oder sollen sie einmal für AWS und einmal für IBM sein?

**Comment by PatrickEbner** [comment]
Old estimate: 8
