### ISSUE TITLE
Add a guided tutorial how to add a new pilot

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#71]
## Problem Statement

Qunicorn is a growing platform and should support upcoming services from quantum hardware vendors.

## References

<https://github.com/OpenTOSCA/opentosca-docker/blob/main/docs/tutorial-model-and-deploy.md>

## Expected Behavior

Following the guide should lead to a valid implementation of a new pilot.

## Tasks

- [x] Collect all the necessary information (what to add where in the code)
- [x] Document the steps with screenshots/gifs
- [x] Also document how a proper test for the should be build
- [x] Add a Qunicorn Tutorial Section in rtd
- [x] Insert the tutorial in rtd
- [x] Also add a showcase, that it works using a minimal example

## Notes

There could be much code in the screenshots as it is a programming task to add a new pilot. Showing Codesnippets can be useful, especially when they are copy-paste code for new pilots.

Is dependent on #115
