### ISSUE TITLE
Create a docker-compose

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#72]
## Problem Statement

Qunicorn has many components, but even more when other components are added.
It should be possible to start it automatically

## References

<https://github.com/OpenTOSCA/opentosca-docker/blob/main/docker-compose.yml>
<https://github.com/UST-QuAntiL/qhana-plugin-runner/blob/main/docker-compose.yml>

## Expected Behavior

A docker compose which is easily startet via `docker compose up` command.

## Tasks

- [x] Create a docker compose file containing the basic setup
- [x] Use the standard container images like redis:latest
- [x] Enhance the setup by using a database container
- [ ] Test the docker compose on different systems (if available)
- [x] Add the docker compose to the documentation, especially to the readme
- [x] Add an overview of the docker compose as picture in the docu (see below an example)

## Notes

Look at the already runnable [branch](https://github.com/SeQuenC-Consortium/qunicorn-core/tree/fix/postgres-authentication)

The first version should be:

Qunicorn-core Server mode, Redis, Qunicorn-worker mode, Database container.
The database container is flexible. Could be postgres, mariadb, ...

An optional, but very nice addition would be a overview of the docker compose landscape, that looks like this:

<details><summary>(click to expand)</summary>

![image](https://github.com/SeQuenC-Consortium/qunicorn-core/assets/56876774/d1306f24-b0df-4632-8d3f-f707303c6e6f)

</details>
