### ISSUE TITLE
Create a kubernetes deployment in a minikube cluster

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#73]
## Problem Statement

With a growing framework, it is necessary to have a deployment automation

## Expected Behavior

The lokal kubernetes cluster works similar to #72 but with kubernetes features like autoscaling, etc.

## Tasks

- [x] Create a kubeconfig.yaml with all the necessary containers
- [x] Add the documentation of how to setup the kubernetes cluster
- [ ] Add the tutorial steps to the Tutorial section in rtd

## Notes

Issue to be refinded!

**Comment by st161630** [comment]
Discussion with other Team Members after Docker Issue has been completed
