### ISSUE TITLE
Complete and Fix Apis

### ISSUE THREAD

**Issue by st161630** [SeQuenC-Consortium/qunicorn-core#77]
## Problem Statement

Some APIs still have not been fully implemented. (e.g. Provider).
Replace NotImplemented Exceptions with logic acessing the DB etc. 

## Expected Behavior

Have a fully functional API (with room for later expansion).

## Tasks

- [x] Remove Pause Job API
- [x] Check and Complete Provider API
- [x] Check and Complete User API

Other APIs are part of other tickets, or currently in progress.

## Notes

related Issue: #78 
Cancel functionality has been moved to #104
