### ISSUE TITLE
Complete Device API

### ISSUE THREAD

**Issue by BonnetGa** [SeQuenC-Consortium/qunicorn-core#79]
## Problem Statement

Complete the Device API

## Expected Behavior

Have a fully functional API (with room for later expansion).

## Tasks

- [x] Get Device by ID
- [x] Get All Devices
- [x] Get Status/Calibration/Jobs

Other APIs are part of other tickets, or currently in progress.

## Notes

related Issue: #78  and #77
