### ISSUE TITLE
In-Request Execution with the QRISP-Framework

### ISSUE THREAD

**Issue by GeorgDaniel** [SeQuenC-Consortium/qunicorn-core#84]
## Problem Statement

The Goal is to include a feature to execute a quantum circuit on a target device where the quantum circuit code lies in the request.

## References

<details><summary>Documentation Links (click to expand)</summary>
<p>

[https://github.com/fraunhoferfokus/Qrisp](url)
[https://www.qrisp.eu](url)

</p>
</details> 

## Tasks

- [ ] Familiarize yourself with QRISP (not too much)
- [ ] Implement the execute request for executing RUNNER Tasks with Qrisp
- [ ] Results should be handeled similar to IBM
- [ ] Write Tests for the QRISP Pilot

## Notes

The quantum circuit is most likely in the OpenQASM format. This format is the equivalent to a classical assembler code and can be encoded in a String.

The Tutorial on their site uses the kolkata IBM backend, which is not available.
Supporting IBM backends including the simulator using their VirtualBackend is enough for this issue.

**Comment by BonnetGa** [comment]
Resolved with #115 and #116
