### ISSUE TITLE
Add provider to device file

### ISSUE THREAD

**Issue by ArneBartenbach** [SeQuenC-Consortium/qunicorn-core#85]
## Problem Statement
Currently we have a json to insert all devices from IBM in the database.
This needs to be enhanced to support also the insertion of devices of other provider.

Use the providerID entry to match the devices to the provider so also new devices like the AWS_local_simulator can be manually added to the devices file.

## Tasks
- [x] Use the provider_id of the json entries of "qunicorn_devices.json" to distinguish between the providers
- [x] Add the AWS local simulator to the json
- [x] Extend the method "add_devices" to insert also the AWS device
